### PR TITLE
fix!: Use %b (and Compatible Escaping) for Quoted strings

### LINKED ISSUE #25: Generated dollar-quote escape sequences are Bash-specific (in practice)
For the code
```
RUN apt-get update && \
	apt-get -y install --no-install-recommends
```
… Bash-TPL generates:
```
printf "%s\n" RUN\ apt-get\ update\ \&\&\ \\
printf "%s\n" $'\tapt-get -y install --no-install-recommends'
```

Which prints
```
RUN apt-get update && \
$\tapt-get -y install --no-install-recommends
```
…when run with Dash.

As the readme says, the generated scripts are not supposed to use Bashisms.

> The shell scripts that Bash-TPL generates are not intended to be Bash-specific.

The feature in question is, as far as I can tell, part of POSIX 2024, but it’ll be a while until support for it is added to all shells.
Dash has committed [a patch](https://git.kernel.org/pub/scm/utils/dash/dash.git/commit/?id=776424a8f9158bfe9f53aa55f931af9f73437caf) that adds it just a few hours ago.

I’m not sure whether it’s worth fixing it, but I guess this behavior should be at least documented here on the bug tracker.

### PR DESCRIPTION
**Pull request by TekWizely**
closes #25  

Looks like I was supposed to be using `%b` all along:

* https://www.unix.com/man-page/posix/1posix/printf/

> ... An  additional  conversion  specifier character, b , shall be supported as follows. The argument shall be taken to be a string that may contain backslash-escape sequences

It appears that many shells treat %s and %b similarly, which is likely why I didn't discover the issue earlier.

As a posix printf standard, this should just be an improvement, correcting behavior for shells like DASH.

---

cc: @0xEAB lemme know if you have time to give this a test drive.

### CODE REVIEW

**Comment by 0xEAB** [comment]
#### `cat bug.txt`

```
RUN apt-get update && \
	apt-get -y install --no-install-recommends
```

#### `./bash-tpl_patched bug.txt | /bin/dash`

```
RUN apt-get update && \
$	apt-get -y install --no-install-recommends
```

**Comment by TekWizely** [comment]
Closing this MR as its not a working solution to the problem ...

**Comment by TekWizely** [comment]
@0xEAB I've re-opened this MR after having a chance to do some research - I've implemented a `printf %b` compatible escape function which I hope doesn't break other users once its released :) 

I'd appreciate if you had a had a chance to give it another try!

**Comment by 0xEAB** [comment]
Works for me.

**Pull request merged**
