### PR TITLE
feat: Support .INCLUDE?

### LINKED ISSUE #18: a conditional .INCLUDE throws error when file does not exist
```
% if [[ -f  "$BUILD_SRC/Dockerfile" ]]; then
 .INCLUDE "$BUILD_SRC/Dockerfile"
% fi
```

if the file  `"$BUILD_SRC/Dockerfile"` does not exist then the .INCLUDE statement is ignored BUT bash-tpl  STILL seems to want to check that the .INCLUDE file exists thus throwing an error.  This is unexpected.

```
File not found: '/data/Hacking/computing/docker/uci-docker-nextcloud/src/Dockerfile'
/dev/fd/63: line 142: syntax error near unexpected token `fi'
/dev/fd/63: line 142: `fi'
```

if `"$BUILD_SRC/Dockerfile"` exists it all works as expected.

### PR DESCRIPTION
**Pull request by TekWizely**
Adds ability to try to include potentially missing files. Introduces .INCLUDE? directive.

docs: Adds docs for new directive
test: Adds tests for conditional includes
test: Adds ability to test against stderr
chore: updates CI Bats version to 1.7.0
chore: Sets bats_require_minimum_version to 1.7.0
chore: Adds 'shellcheck source' doc to all bash-tpl sourcing lines

--

closes #18 
cc: @dkebler

### CODE REVIEW

**Comment by TekWizely** [comment]
@dkebler Please give this PR a test drive if you have time - would love to get some feedback before merging it.

**Comment by dkebler** [comment]
Sorry just saw this comment but will give it a try in the next week.  

BTW bash-tpl has turned out to be a critical component for several involved/flexible bash scripts so thanks again!

**Comment by TekWizely** [comment]
@dkebler Just checking in to see if you had a chance to try the feature?

**Comment by dkebler** [comment]
Ok, finally got some time to try it out.  Yes .INCLUDE? is working so thx for adding this.  No need for a dummy file now :).

**Pull request merged**
